add_word created
backdownof/word-whisper-bot pull request #2
Opened 2024-04-10 16:48 UTC by slavspart

Во views.words cоздал корутину add_word и переработал next_word.
Добавил в классы Callback и Button константы DELETE_LEARNING и ADD_LEARNING.

2024-04-11 05:56 UTC, backdownof commented on views/constants/callbacks.py
> +    # Убрал to из названия колбэка и кнопки (мне показалось так логичнее и проще)
эти коменты в коде не указываем. Оставляем на коменте

2024-04-11 05:59 UTC, backdownof commented on views/constants/callbacks.py
> +    ADD_LEARNING = "add_learning"
и нужно придерживаться кода. Если строки в одинарных ковычках рядом, то оставляем одинарные, если в двойных - двойные

2024-04-11 05:59 UTC, backdownof commented on views/words.py
> +# поправил импорты по PEP
коммент

2024-04-11 06:35 UTC, backdownof commented on views/words.py
> +from aiogram import types, Router, F
я обычно отделяю сторонние библиотеки, от внутренних модулей, чтобы было проще искать. поэтому aiogram я бы выше поднял.

2024-04-11 06:36 UTC, backdownof commented on views/words.py
> +    keyboard_data = [
логические блоки пустыми строками не забывай отделять

2024-04-11 06:38 UTC, backdownof commented on views/words.py
> +        (Button.ADD_LEARNING, f'{Callback.ADD_LEARNING}_{word_and_translation[0].id}')
я тут подумал, что и правда не лишним будет добавить проверку на то, что у пользователя слово нет еще в списке, перед показом кнопки

2024-04-11 06:38 UTC, backdownof commented on views/words.py
>      if not word_and_translation:
пустые строки. иначе код в лапшу превращается

2024-04-11 06:38 UTC, backdownof commented on views/words.py
а эта пустая строка как раз не нужна

2024-04-11 06:39 UTC, backdownof commented on views/words.py
> +
лишняя пустая строка

2024-04-11 06:40 UTC, backdownof commented on views/words.py
> +    models.DBSession.add(new_user_word)
в models/__init__.py для удобства добавлена обертка. для add, чтобы можно было вызывать new_user_word.add()

2024-04-11 06:41 UTC, backdownof commented on views/words.py
> +    word = models.DBSession.query(models.Word).filter_by(id=word_id).first()
добавить пустую строку. И можно более кратко записать. models.Word.query.get(word_id)

2024-04-11 06:41 UTC, backdownof commented on views/words.py
> +        )
отступ лишний

2024-04-11 06:41 UTC, backdownof commented on views/words.py
> +        text = f'Слово <b>{word}</> добавлено в карточки для изучения!',
пробелы лишние вокруг '='

2024-04-11 06:42 UTC, backdownof requested changes

2024-04-11 06:42 UTC, backdownof commented on views/words.py
> +        )
отступ лишний

2024-04-13 08:11 UTC, slavspart commented
Поправил замечания и добавил проверку, чтобы при нажатии next_word не выдавались слова, которые были добавлены. Запрос сделал в стиле SQLAlchemy 2.0 (execute(select...)). Пишут, что query устаревший, но поддерживаемый синтаксис https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html. 
Предлагаю подумать, дальше будем использовать execute(select) или query?

2024-04-23 18:51 UTC, slavspart commented
Вставил согласованный вариант синтаксиса запроса для получения word_and_translation из базы.

2024-04-24 04:14 UTC, backdownof approved these changes
Надо убрать лишние пробелы. В остальном - молодец! Будем мержить

2024-04-24 04:14 UTC, backdownof commented on views/words.py
> +
```suggestion

```

2024-04-24 04:14 UTC, backdownof commented on views/words.py
>          user_levels.append('')
```suggestion
        user_levels.append('')

```

2024-04-24 04:14 UTC, backdownof commented on views/words.py
> +
```suggestion

```

2024-04-24 04:14 UTC, backdownof commented on views/words.py
> +
```suggestion

```

2024-04-24 04:14 UTC, backdownof commented on views/words.py
> +    new_user_word.word_id = word_id
```suggestion

    new_user_word = models.UserWord()
    new_user_word.user_id = user.id
    new_user_word.word_id = word_id
```

2024-04-24 11:25 UTC, merged